### ISSUE TITLE
Virtual glider path?

### ISSUE THREAD

**Issue by rsignell-usgs** [martalmeida/okean#1]
Okay, I'm being a bit lazy here, but can this package do a virtual glider path through a ROMS model given (x,y,z,t)?  Or (x,y,t)?

**Comment by martalmeida** [comment]
I did a class for that some time ago. It was just a test but was working fine (with x,y,z,t coords). It is not included in okean. I will try to locate it and place it in some development folder for now.

**Comment by rsignell-usgs** [comment]
@martalmeida , that would be great!  
We would love to take a look.  
Did it require that grids have even spacing, or did it work with general curvilinear ROMS grids?

**Comment by rsignell-usgs** [comment]
@martalmeida , I'm back in the office and thinking about virtual glider paths.   We have John Wilkin's matlab version here:  https://github.com/nctoolbox/nctoolbox/blob/master/cdm/utilities/slicing/nc_genslice.m
that we are thinking of using as a starting point.  

One of the challenges is figuring out what size chunks to read out of the netCDF file (or OPeNDAP dataset) to make the routine fast. 

Here they just pull all the data that brackets the bounding box of the glider in the bracketing time steps: https://github.com/nctoolbox/nctoolbox/blob/master/cdm/utilities/slicing/nc_genslice.m#L233-L248

Do you take a similar approach?

**Comment by martalmeida** [comment]
@rsignell-usgs, I just found my tool and it extracts data from model output in a x,y,t path. It extracts the whole water column (with a 3d var), but that can be changed easily.  It works with any ROMS grid, and loads only the minimum data needed for the interpolations (at each time, not the whole bbox).
I must do some very small updates to the code. Can you send me an example to test? OPeNDAP link, varname, x,y,t(z) vectors?

**Comment by martalmeida** [comment]
@rsignell-usgs, I discovered some data to test and made some developments in the code. I created a notebook about this: https://github.com/martalmeida/okean/blob/master/roms_glider.ipynb
I found that the fastest way may be to get all the data, including lots of unnecessary data like nc_genslice.m does. In my code I added an option to split data access in time, in which user can provide a vector of time indices. Now the question is how to find the indices! And the solution may be found in cluster analysis, which will decrease the extra data downloaded. I let that for later...

**Comment by rsignell-usgs** [comment]
@martalmeida , woohoo!  Super cool!   I'm going to give it a try right now!

**Comment by rsignell-usgs** [comment]
Working!   Just to prove it, my notebook is here:
http://nbviewer.ipython.org/gist/rsignell-usgs/96dcf84ba0a340d2cfaa
the only thing I changed is adding the actual glider data and making the plots wider. ;-)

Partial screen grab:
![7-6-2015 11-00-02 am](https://cloud.githubusercontent.com/assets/1872600/8525368/7328fa40-23ce-11e5-90a6-698ab34ebedf.png)

**Comment by rsignell-usgs** [comment]
Closing this issue since there is a way to extract glider sections, even though improvements are possible.
