### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rsignell-usgs** [martalmeida/okean#3]
@martalmeida , I remember seeing documentation for okean somewhere.  Can you please provide the URL?

**Comment by martalmeida** [comment]
@rsignell-usgs, it was probably this http://pong.tamu.edu/~mma/py/okean/overview.php. But I am just now working on tutorials using recent okean features. I will have some ipython notebooks ready very soon.

**Comment by rsignell-usgs** [comment]
@martalmeida , awesome.   Having some notebooks will be super useful.

**Comment by jz-ocrs** [comment]
@martalmeida The documentation link does not work now. Is there any other way to get the documentation?

**Comment by martalmeida** [comment]
The site has been down. It is up now. You may also want to check:
https://github.com/martalmeida/okean/blob/master/okean_documentation.ipynb
Anyway, both may be a bit outdated...

**Comment by hafez-ahmad** [comment]
I tried both links but those are not valid.

**Comment by martalmeida** [comment]
Most of the documentation is now in my github site:
https://martalmeida.github.io/notebooks/
It will probably stay here for a while. I will try to add more notebooks in the near future.
