### ISSUE TITLE
slicek issue

### ISSUE THREAD

**Issue by Dooruk** [martalmeida/okean#6]
I am trying to use a simple licek command 

x,y,z,s=r.slicek('salt',-1,1)

Then get ther error:
cannot unpack non-iterable Data object

I get the same error using okean package for multi-variate outputs (x,y,z,s) but the single output commands are working. I used the same code for Python 2 version a year ago and it would work, so I was wondering if there is a version mismatch for the definitions?

**Comment by martalmeida** [comment]
In recent okean versions the output of roms.His slices is a Data object. This object has several attributes and methods. So you can do:
o=r.slicek('salt',-1,1)
o.plot() # quick visualisation
x,y,s=o.x,o.y,o.v # there is also o.z, o.t, ...
pl.pcolormesh(x,y,s)
The new code should work with python 2 and 3
best

**Comment by Dooruk** [comment]
Thank you, it works now.
